# Don't print a new line at the start of the prompt
add_newline = false
# Pipes ╰─ ╭─
# Powerline symbols                                     
# Wedges 🭧🭒 🭣🭧🭓
# Random noise 🬖🬥🬔🬗

# format = """
# $cmd_duration$username$hostname $directory $git_branch
# $character
# """
format = """
 $sudo$cmd_duration$directory$username$rust$python$git_branch$git_commit
 $character
"""

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[• ](bold fg:white) "
error_symbol = "[• 󰅙](bold fg:#eba0ac) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
style = "bg: #eba0ac"
symbol = "󰘬"
truncation_length = 4
truncation_symbol = ""
format = " • [](bold fg:#eba0ac)[$symbol $branch(:$remote_branch)](fg:#1e1e2e bg:#eba0ac)[](bold fg:#eba0ac)"

[git_commit]
commit_hash_length = 4
tag_symbol = " "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_status]
conflicted = " 🏳 "
ahead = " 🏎💨 "
behind = " 😰 "
diverged = " 😵 "
untracked = " 🤷 ‍"
stashed = " 📦 "
modified = " 📝 "
staged = '[++\($count\)](blue)'
renamed = " ✍️ "
deleted = " 🗑 "

[python]
symbol = '󰌠'
format = '[[ •• ](bold fg:white)[](bold fg:#a6e3a1)[$symbol $virtualenv](bold bg:#a6e3a1 fg:#1e1e2e)[](bold fg:#a6e3a1)]($style)'

[rust]
symbol = '󱘗'
format = '[[ •• ](bold fg:white)[](bold fg:#fab387)[$symbol $version](bold bg:#fab387 fg:#1e1e2e)[](bold fg:#fab387)]($style)'

[docker_context]
symbol = ""
format = '[[ •• ](bold fg:white)[](bold fg:#74c7ec)[$symbol $context](bold bg:#74c7ec fg:#1e1e2e)[](bold fg:#74c7ec)]($style)'

[hostname]
ssh_only = false
format =  "[•$hostname](bg:cyan bold fg:black)[](bold fg:cyan )"
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = false
threshold = -1
symbol = " "
style = "bold dimmed blue"

[time]
disabled = true
format = ' [\[ $time \]]($style) '
time_format = "%T"

[username]
style_user = "bold bg:white fg:#1e1e2e"
style_root = "red bold"
format = "[](bold fg:white)[$user]($style)[](bold fg:white)"
disabled = false
show_always = true

[sudo]
symbol = " "
format = "[(bold fg:white)[](bold fg:#f38ba8)[$symbol](bold bg:#f38ba8 fg:#1e1e2e)[](bold fg:#f38ba8)[ •• ](bold fg:white)]($style)"
disabled = false

[directory]
home_symbol = "  "
read_only = "  "
style = "bg:#f5c2e7 fg:#1e1e2e"
truncation_length = 6
truncation_symbol = "••/"
format = '[](bold fg:#f5c2e7)[$path ]($style)[](bold fg:#f5c2e7) •• '


[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "
#
"sda1" = " 󰋊 "
"Obsidian" = "  "
"Books" = "  "
"GitHub" = "  "
"PortProton" = " 󰸷 " 
"Games" = " 󰊗 "
"SteamLibrary" = "  "
#
".android" = "  "
".cache" = " 󰃨 "
".config" = " "
".gnupg" = " 󰢬 "
".java" = "  "
".icons" = "  "
".mozilla" = "  "
".ssh" = " 󰢬 "
".vscode" = "  "
#
"hyprland" = "  "
"bspwm" = "  "
"dwm" = "  "

[cmd_duration]
min_time = 0
format = '[](bold fg:#cba6f7)[ $duration](bold bg:#cba6f7 fg:#1e1e2e)[](bold fg:#cba6f7) •• '
