general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(f5c2e7ee) rgba(cba6f7ee) 45deg
    col.inactive_border = rgba(595959aa)

    layout = dwindle

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = true
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 15
    shadow {
        enabled = true
        range = 30
        offset = 2 3
        render_power = 3
        color = rgba(00000066)
    }

    blur {
        enabled = true
        size = 6
        passes = 3
        new_optimizations = true
        ignore_opacity = true
        xray = false
    }
}

