general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    gaps_in = 3
    gaps_out = 6
    border_size = 1
    col.active_border = rgba(ec5d2aee) rgba(ec5d2aee) 45deg
    col.inactive_border = rgba(595959aa)

    layout = dwindle

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = true
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 0
    shadow {
        enabled = false
        range = 30
        offset = 2 3
        render_power = 3
        color = rgba(00000066)
    }

    blur {
        enabled = true
        size = 6
        passes = 3
        new_optimizations = true
        ignore_opacity = true
        xray = false
    }
}
