#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
lxpolkit &
nvidia-settings --load-config-only
alsactl init
pactl set-sink-volume alsa_output.pci-0000_0a_00.4.analog-stereo 50%
pactl set-source-volume alsa_input.pci-0000_0a_00.4.analog-stereo 35%
numlockx &
nitrogen --restore &
pgrep -x dunst > /dev/null || dunst &
picom -b &
xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/launch.sh
pgrep -x conky > /dev/null || conky &
gwe --hide-window &
flameshot &
syncthing -no-browser -no-restart -logflags=0 &

bspc monitor HDMI-0 -d 󰈹     󰸷
bspc monitor DVI-D-0 -d 󰓓  󱥁 

bspc config border_width            3
bspc config window_gap              5
bspc config normal_border_color     "#1c1b20"
bspc config active_border_color     "#a38f91"
bspc config focused_border_color    "#8a5f58"
bspc config presel_feedback_color   "#8a5f58"

bspc config focus_follows_pointer   true
bspc config borderless_monocle      true
bspc config gapless_monocle         true

export XDG_CURRENT_DESKTOP=bspwm
export XDG_SESSION_DESKTOP=bspwm
export _JAVA_AWT_WM_NONREPARENTING=1 

#windows class, xprop | grep WM_CLASS and xwininfo to use
bspc rule -a Gnome-calculator state=floating follow=on size=370x500
bspc rule -a org.gnome.clocks state=floating floating=on size=400x550
bspc rule -a Gcolor3 state=floating floating=on size=800x315
bspc rule -a IVPN state=floating floating=on size=760x600
bspc rule -a steam desktop='^7' state=tiled follow=no
bspc rule -a QjackCtl state=floating follow=on
bspc rule -a Yad state=floating follow=on
bspc rule -a stalonetray state=floating follow=on
