#!/bin/bash
workspaces() {

    ws1="1"
    ws2="2"
    ws3="3"
    ws4="4"
    ws5="5"
    ws6="6"
    ws7="7"
    ws8="8"
    ws9="9"
    ws0="0"

    # Unoccupied
    un="0"

    # check if Occupied
    o1=$(bspc query -D -d .occupied --names | grep "$ws1" || echo c)
    o2=$(bspc query -D -d .occupied --names | grep "$ws2" || echo c)
    o3=$(bspc query -D -d .occupied --names | grep "$ws3" || echo c)
    o4=$(bspc query -D -d .occupied --names | grep "$ws4" || echo c)
    o5=$(bspc query -D -d .occupied --names | grep "$ws5" || echo c)
    o6=$(bspc query -D -d .occupied --names | grep "$ws6" || echo c)
    o7=$(bspc query -D -d .occupied --names | grep "$ws7" || echo c)
    o8=$(bspc query -D -d .occupied --names | grep "$ws8" || echo c)
    o9=$(bspc query -D -d .occupied --names | grep "$ws9" || echo c)
    o0=$(bspc query -D -d .occupied --names | grep "$ws0" || echo c)

    # check if Focused
    f1=$(bspc query -D -d focused --names | grep "$ws1" )
    f2=$(bspc query -D -d focused --names | grep "$ws2" )
    f3=$(bspc query -D -d focused --names | grep "$ws3" )
    f4=$(bspc query -D -d focused --names | grep "$ws4" )
    f5=$(bspc query -D -d focused --names | grep "$ws5" )
    f6=$(bspc query -D -d focused --names | grep "$ws6" )
    f7=$(bspc query -D -d focused --names | grep "$ws7" )
    f8=$(bspc query -D -d focused --names | grep "$ws8" )
    f9=$(bspc query -D -d focused --names | grep "$ws9" )
    f0=$(bspc query -D -d focused --names | grep "$ws0" )

    ic_1="󰈹"
    ic_2=""
    ic_3=""
    ic_4=""
    ic_5=""
    ic_6="󰸷"
    ic_7="󰓓"
    ic_8=""
    ic_9="󱥁"
    ic_0=""

    if [ "$f1" ]; then
        ic_1="󰈹"
    elif [ "$f2" ]; then
        ic_2=""
    elif [ "$f3" ]; then
        ic_3=""
    elif [ "$f4" ]; then
        ic_4=""
    elif [ "$f5" ]; then
        ic_5=""
    elif [ "$f6" ]; then
        ic_6="󰸷"
    elif [ "$f7" ]; then
        ic_7="󰓓"
    elif [ "$f8" ]; then
        ic_8=""
    elif [ "$f9" ]; then
        ic_9="󱥁"
    elif [ "$f0" ]; then
        ic_0=""
    fi

    echo  "(eventbox :cursor 'pointer' (box :class 'works' :orientation 'h' :spacing 5 :space-evenly 'false' (button :onclick 'bspc desktop -f $ws1' :class '$un$o1$f1' '$ic_1') (button :onclick 'bspc desktop -f $ws2' :class '$un$o2$f2'  '$ic_2') (button :onclick 'bspc desktop -f $ws3' :class '$un$o3$f3' '$ic_3') (button :onclick 'bspc desktop -f $ws4' :class '$un$o4$f4' '$ic_4') (button :onclick 'bspc desktop -f $ws5' :class '$un$o5$f5' '$ic_5')  (button :onclick 'bspc desktop -f $ws6' :class '$un$o6$f6' '$ic_6')  (button :onclick 'bspc desktop -f $ws7' :class '$un$o7$f7' '$ic_7')  (button :onclick 'bspc desktop -f $ws8' :class '$un$o8$f8' '$ic_8')  (button :onclick 'bspc desktop -f $ws9' :class '$un$o9$f9' '$ic_9')  (button :onclick 'bspc desktop -f $ws0' :class '$un$o0$f0' '$ic_0')))"
}

workspaces
bspc subscribe desktop_focus node_add node_remove 2> /dev/null | while read line; do
    workspaces
done
