#!/usr/bin/env bash
if [ "$(xset -q | sed -rn 's/.*LED mask.*(.)[[:xdigit:]]{3}$/\1/p')" == "0" ]; then
  echo "󰌌 us"
elif [ "$(xset -q | sed -rn 's/.*LED mask.*(.)[[:xdigit:]]{3}$/\1/p')" == "1" ]; then
  echo "󰌌 ru"
fi

