#!/bin/bash
GentooEnvPath=/mnt/sda1/gentoo
sudo mount --types proc /proc $GentooEnvPath/proc 
sudo mount --rbind /sys $GentooEnvPath/sys
sudo mount --make-rslave $GentooEnvPath/sys
sudo mount --rbind /dev $GentooEnvPath/dev
sudo mount --make-rslave $GentooEnvPath/dev
sudo mount --bind /run $GentooEnvPath/run
sudo mount --make-slave $GentooEnvPath/run
if [[ -f "$GentooEnvPath/usr/bin/zsh" ]]; then
  echo "Zsh founded. Chrooting..."
  su -c "chroot $GentooEnvPath /bin/zsh"
else
  echo "Zsh not founded. Chrooting in bash..."
  su -c "chroot $GentooEnvPath /bin/bash"
fi
