#!/bin/bash
sudo mount --types proc /proc /mnt/sda1/gentoo/proc 
sudo mount --rbind /sys /mnt/sda1/gentoo/sys
sudo mount --make-rslave /mnt/sda1/gentoo/sys
sudo mount --rbind /dev /mnt/sda1/gentoo/dev
sudo mount --make-rslave /mnt/sda1/gentoo/dev
sudo mount --bind /run /mnt/sda1/gentoo/run
sudo mount --make-slave /mnt/sda1/gentoo/run
if [[ -f "/mnt/sda1/gentoo/usr/bin/zsh" ]]; then
  echo "Zsh founded. Chrooting..."
  su -c "chroot /mnt/sda1/gentoo/ /bin/zsh"
else
  echo "Zsh not founded. Chrooting in bash..."
  su -c "chroot /mnt/sda1/gentoo/ /bin/bash"
fi
