exec-once = /usr/bin/sudo /root/nvgpu-overclock/run-nvgpu-overclock
exec-once = hyprlock

exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec = alsactl init
exec = pactl set-default-sink alsa_output.pci-0000_0a_00.4.analog-stereo
exec = pactl set-sink-volume alsa_output.pci-0000_0a_00.4.analog-stereo 50%
exec = pactl set-source-volume alsa_input.pci-0000_0a_00.4.analog-stereo 35%
exec-once = swww-daemon
#exec = swww img Pictures/Wallpapers/343434344343.jpg --transition-type center
exec = swww img Pictures/Wallpapers/LIVE/girl-katana.1920x1080.gif --transition-type center
exec = hyprshade on ~/.config/hyprshade/shaders/vibrance.glsl
exec = ags
exec = /home/restranger/.config/nwg-dock-hyprland/nwg-dock-hyprland.sh
