source = ~/.config/hypr/pc/autostart.conf
source = ~/.config/hypr/pc/bind.conf
source = ~/.config/hypr/pc/enviroments.conf
source = ~/.config/hypr/pc/monitor.conf
source = ~/.config/hypr/themes/imports.conf
