exec-once = hyprlock

exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec = swww-daemon
exec = swww img /home/restranger/Pictures/Wallpapers/yosemite.png --transition-type center
exec-once = ags
#exec-once = hypridle
exec-once = hyprshade on /home/restranger/.config/hyprshade/shaders/vibrance.glsl
